In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler,RobustScaler
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_csv('Housing.csv')
df = data

In [5]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [7]:
df.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [9]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [11]:
df['HighPrice'] = (df['price']>5000000).astype(int)

In [13]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished   
1                no             yes        3       no        furnished   
2                no              no        2      yes   semi-furnished   
3                no             yes        3      yes        furnished   
4                no             yes        2       no        furnished   
..              ...             ...      ...      ...              ...   
540              no              no        2       no      unfurnished   
541              no              no        0       no   semi-furnished   
542              no              no        0       no      unfurnished   
543              no              no        0       no        furnished   
544              no              no        0       no      unfurnished   

     HighPrice  
0            1  
1            1  
2            1  
3            1  
4            1  
..         ...  
540          0  
541          0  
542          0  
543          0  
544          0  

[545 rows x 14 columns]

In [15]:
#feature selectiom and target
x = df[['area','bedrooms','bathrooms','stories']]
y = df['HighPrice'] 

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state = 35)

In [19]:
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled

array([[0.46391753, 0.6       , 0.        , 1.        ],
       [0.14398625, 0.4       , 0.        , 0.33333333],
       [0.65463918, 0.4       , 0.        , 0.        ],
       ...,
       [0.16804124, 0.2       , 0.        , 0.        ],
       [0.29621993, 0.4       , 0.66666667, 0.33333333],
       [0.01752577, 0.8       , 0.        , 0.33333333]])

In [21]:
x_test_scaled = scaler.fit_transform(x_test)
x_test_scaled

array([[0.73224785, 0.        , 0.        , 0.        ],
       [0.09090909, 0.33333333, 0.        , 0.33333333],
       [0.12437811, 0.33333333, 0.        , 0.33333333],
       [0.18950701, 0.33333333, 0.        , 0.33333333],
       [0.1641791 , 0.33333333, 0.        , 0.33333333],
       [0.38037087, 0.33333333, 0.5       , 0.66666667],
       [0.09407508, 0.        , 0.        , 0.        ],
       [0.33785617, 0.33333333, 0.        , 0.        ],
       [0.17865219, 0.        , 0.        , 0.        ],
       [0.37774763, 0.33333333, 0.        , 0.33333333],
       [0.42333786, 0.33333333, 0.        , 0.        ],
       [0.43012212, 0.33333333, 0.5       , 0.        ],
       [0.39755767, 0.66666667, 0.5       , 0.33333333],
       [0.14066033, 0.66666667, 0.        , 0.33333333],
       [0.24016282, 0.33333333, 0.5       , 1.        ],
       [0.41293532, 0.33333333, 0.5       , 0.33333333],
       [0.39620081, 0.33333333, 0.5       , 1.        ],
       [0.10447761, 0.33333333,

In [23]:
x_train

area  bedrooms  bathrooms  stories
247   8400         4          1        4
232   3745         3          1        2
64   11175         3          1        1
427   2145         3          1        2
491   2640         2          1        1
..     ...       ...        ...      ...
184   3000         3          2        2
249   4990         4          2        2
448   4095         2          1        1
33    5960         3          3        2
271   1905         5          1        2

[436 rows x 4 columns]

In [25]:
x_test

area  bedrooms  bathrooms  stories
224  10240         2          1        1
382   3150         3          1        2
301   3520         3          1        2
387   4240         3          1        2
329   3960         3          1        2
..     ...       ...        ...      ...
348   3150         2          2        1
130   4800         3          1        1
385   3640         2          1        1
28    7950         5          2        2
386   3850         3          1        1

[109 rows x 4 columns]

In [27]:
model = LogisticRegression()

In [29]:
#training model
model.fit(x_train, y_train)

E:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [33]:
y_predict = model.predict(x_test)
y_predict
#predicted value based on test data

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [35]:
#actal value present in out data
y_test

224    0
382    0
301    0
387    0
329    0
      ..
348    0
130    1
385    0
28     1
386    0
Name: HighPrice, Length: 109, dtype: int32

In [72]:
#accuray for unscaled data
accuracy_oflr = accuracy_score(y_predict,y_test)
print(f'Acuracy of the model: {accuracy_oflr}')

Acuracy of the model: 0.7614678899082569


In [74]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.74      0.92      0.82        64
           1       0.83      0.53      0.65        45

    accuracy                           0.76       109
   macro avg       0.78      0.73      0.73       109
weighted avg       0.77      0.76      0.75       109



In [45]:
x_test

area  bedrooms  bathrooms  stories
224  10240         2          1        1
382   3150         3          1        2
301   3520         3          1        2
387   4240         3          1        2
329   3960         3          1        2
..     ...       ...        ...      ...
348   3150         2          2        1
130   4800         3          1        1
385   3640         2          1        1
28    7950         5          2        2
386   3850         3          1        1

[109 rows x 4 columns]

In [56]:
#training model after scalling
model.fit(x_train_scaled,y_train)

LogisticRegression()

In [60]:
#prediction
y_predict_scaled = model.predict(x_test_scaled)
#elivating
#accuracy for scaled data 
accuracy_of_lr = accuracy_score(y_predict_scaled,y_test)
print(f'Acuuracy of the model: {np.round(accuracy_of_lr,2)}')

Acuuracy of the model: 0.77


In [70]:
#confusion Matrix
print(classification_report(y_test,y_predict_scaled))

              precision    recall  f1-score   support

           0       0.75      0.91      0.82        64
           1       0.81      0.58      0.68        45

    accuracy                           0.77       109
   macro avg       0.78      0.74      0.75       109
weighted avg       0.78      0.77      0.76       109

